# Generated by Django 3.1.7 on 2021-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('alias', models.SlugField(verbose_name='alias')),
                ('snippet', models.TextField(verbose_name='snippet')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shortener',
                'verbose_name_plural': 'shorteners',
            },
        ),
    ]
