# Generated by Django 3.1.7 on 2021-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210313_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='snippet',
            field=models.TextField(blank=True, null=True, verbose_name='snippet'),
        ),
    ]
