# Generated by Django 3.1.7 on 2021-03-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20210314_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=5, verbose_name='locale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='terakhir diperbaharui')),
                ('shortener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.shortener')),
            ],
        ),
    ]
