# Generated by Django 3.1.7 on 2021-03-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'statistic', 'verbose_name_plural': 'statistics'},
        ),
    ]
